case_dict = {'FNLA_YSU_CHRN_GFS_NOSK_3DOM':{'d03':{'color':'green',           'name':'FNL',         'marker':'$\u2665$',     'fill':True}},
             'ERAI_YSU_CHRN_OST_NOSK_4DOM':{'d03':{'color':'blue',            'name':'ERA-I',       'marker':'o',            'fill':True}},
             'ERA5_YSU_CHRN_ER5_NOSK_3DOM':{'d03':{'color':'r',               'name':'ERA5',        'marker':'p',            'fill':True}},
             
            'DEFLT_NOFL_NOSK' : {'d03' : {'color':'darkblue',  'marker':'$\u2665$',          'name':'ERA-I',          'ls':'-',}},
            'DEFLT_NOFL_SKNT' : {'d03' : {'color':'darkblue',  'marker':'$\u2666$',          'name':'ERA-I_SKNT',     'ls':'--',}},
            'DEFLT_FILL_NOSK' : {'d03' : {'color':'darkblue',  'marker':'$\clubsuit$',       'name':'ERA-I_FILL',     'ls':':',}},
            'DEFLT_FILL_SKNT' : {'d03' : {'color':'darkblue',  'marker':'$\spadesuit$',      'name':'ERA-I_FILL_SKNT','ls':'-.',}},
            'G1SST_NOFL_NOSK' : {'d03' : {'color':'g',         'marker':'$\u2665$',          'name':'G1SST',          'ls':'-',}},
            'G1SST_NOFL_SKNT' : {'d03' : {'color':'g',         'marker':'$\u2666$',          'name':'G1SST_SKNT',     'ls':'--',}},
            'G1SST_FILL_NOSK' : {'d03' : {'color':'g',         'marker':'$\clubsuit$',       'name':'G1SST_FILL',     'ls':':',}},
            'G1SST_FILL_SKNT' : {'d03' : {'color':'g',         'marker':'$\spadesuit$',      'name':'G1SST_FILL_SKNT','ls':'-.',}},
            'MUR1K_NOFL_NOSK' : {'d03' : {'color':'r',         'marker':'$\u2665$',          'name':'MUR',            'ls':'-',}},
            'MUR1K_NOFL_SKNT' : {'d03' : {'color':'r',         'marker':'$\u2666$',          'name':'MUR_SKNT',       'ls':'--',}},
            'MUR1K_FILL_NOSK' : {'d03' : {'color':'r',         'marker':'$\clubsuit$',       'name':'MUR_FILL',       'ls':':',}},
            'MUR1K_FILL_SKNT' : {'d03' : {'color':'r',         'marker':'$\spadesuit$',      'name':'MUR_FILL_SKNT',  'ls':'-.',}},
            'MODIS_NOFL_NOSK' : {'d03' : {'color':'b',         'marker':'$\u2665$',          'name':'MODIS',          'ls':'-',}},
            'MODIS_NOFL_SKNT' : {'d03' : {'color':'b',         'marker':'$\u2666$',          'name':'MODIS_SKNT',     'ls':'--',}},
            'MODIS_FILL_NOSK' : {'d03' : {'color':'b',         'marker':'$\clubsuit$',       'name':'MODIS_FILL',     'ls':':',}},
            'MODIS_FILL_SKNT' : {'d03' : {'color':'b',         'marker':'$\spadesuit$',      'name':'MODIS_FILL_SKNT','ls':'-.',}},
            'OSPOG_NOFL_NOSK' : {'d03' : {'color':'lime',      'marker':'$\u2665$',          'name':'OSPO',           'ls':'-',}},
            'OSPOG_NOFL_SKNT' : {'d03' : {'color':'lime',      'marker':'$\u2666$',          'name':'OSPO_SKNT',      'ls':'--',}},
            'OSPOG_FILL_NOSK' : {'d03' : {'color':'lime',      'marker':'$\clubsuit$',       'name':'OSPO_FILL',      'ls':':',}},
            'OSPOG_FILL_SKNT' : {'d03' : {'color':'lime',      'marker':'$\spadesuit$',      'name':'OSPO_FILL_SKNT', 'ls':'-.',}},
            'OSTIA_NOFL_NOSK' : {'d03' : {'color':'orange',    'marker':'$\u2665$',          'name':'OSTIA',          'ls':'-',}},
            'OSTIA_NOFL_SKNT' : {'d03' : {'color':'orange',    'marker':'$\u2666$',          'name':'OSTIA_SKNT',     'ls':'--',}},
            'OSTIA_FILL_NOSK' : {'d03' : {'color':'orange',    'marker':'$\clubsuit$',       'name':'OSTIA_FILL',     'ls':':',}},
            'OSTIA_FILL_SKNT' : {'d03' : {'color':'orange',    'marker':'$\spadesuit$',      'name':'OSTIA_FILL_SKNT','ls':'-.',}},
            'NAVOK_NOFL_NOSK' : {'d03' : {'color':'m',         'marker':'$\u2665$',          'name':'NAVO',           'ls':'-',}},
            'NAVOK_NOFL_SKNT' : {'d03' : {'color':'m',         'marker':'$\u2666$',          'name':'NAVO_SKNT',      'ls':'--',}},
            'NAVOK_FILL_NOSK' : {'d03' : {'color':'m',         'marker':'$\clubsuit$',       'name':'NAVO_FILL',      'ls':':',}},
            'NAVOK_FILL_SKNT' : {'d03' : {'color':'m',         'marker':'$\spadesuit$',      'name':'NAVO_FILL_SKNT', 'ls':'-.',}},
            'CMC01_NOFL_NOSK' : {'d03' : {'color':'c',         'marker':'$\u2665$',          'name':'CMC',            'ls':'-',}},
            'CMC01_NOFL_SKNT' : {'d03' : {'color':'c',         'marker':'$\u2666$',          'name':'CMC_SKNT',       'ls':'--',}},
            'CMC01_FILL_NOSK' : {'d03' : {'color':'c',         'marker':'$\clubsuit$',       'name':'CMC_FILL',       'ls':':',}},
            'CMC01_FILL_SKNT' : {'d03' : {'color':'c',         'marker':'$\spadesuit$',      'name':'CMC_FILL_SKNT',  'ls':'-.',}},
            'NCEIA_NOFL_NOSK' : {'d03' : {'color':'peru',      'marker':'$\u2665$',          'name':'NCEI',           'ls':'-',}},
            'NCEIA_NOFL_SKNT' : {'d03' : {'color':'peru',      'marker':'$\u2666$',          'name':'NCEI_SKNT',      'ls':'--',}},
            'NCEIA_FILL_NOSK' : {'d03' : {'color':'peru',      'marker':'$\clubsuit$',       'name':'NCEI_FILL',      'ls':':',}},
            'NCEIA_FILL_SKNT' : {'d03' : {'color':'peru',      'marker':'$\spadesuit$',      'name':'NCEI_FILL_SKNT', 'ls':'-.',}},
            'SFILL_NOFL_NOSK' : {'d03' : {'color':'grey',      'marker':'$\u2665$',          'name':'FILL',           'ls':'-',}},
            'SFILL_NOFL_SKNT' : {'d03' : {'color':'grey',      'marker':'$\u2666$',          'name':'FILL_SKNT',      'ls':'--',}},
            'SFILL_FILL_NOSK' : {'d03' : {'color':'grey',      'marker':'$\clubsuit$',       'name':'FILL_FILL',      'ls':':',}},
            'SFILL_FILL_SKNT' : {'d03' : {'color':'grey',      'marker':'$\spadesuit$',      'name':'FILL_FILL_SKNT', 'ls':'-.',}},
            }